- name: Install nginx
  apt:
    name:
      - nginx

- name: Enable the service
  service:
    name: nginx
    enabled: yes

- name: Start the service
  service: 
    name: nginx
    state: started

- name: Copy the index page
  copy:
    src: index.html
    dest: /srv/index.html