- name: Install dependecies
  apt:
    name:
      - adduser
      - libfontconfig1

- name: Download the package
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_7.2.1_amd64.deb
    dest: /tmp/grafana_7.2.1_amd64.deb

- name: Install grafana
  apt:
    deb: /tmp/grafana_7.2.1_amd64.deb

- name: Copy the config
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart grafana

- name: Start grafana
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: Add user backup to grafana group
  user:
    name: backup
    groups: grafana
    append: yes