- name: Install uWSGI packages
  apt:
    name: uwsgi,uwsgi-plugin-python3,python3-pymysql
    
- name: Copy the uWSGI config
  template:
    src: agama_config
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify: Restart uWSGI
    
- name: Enable uWSGI service
  service:
    name: uwsgi
    enabled: yes
