{
 "title": "Lab 7",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "vm1 CPU load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"vm1.verysorry.io:9100\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) or (clamp_max(irate(node_cpu{instance=\"vm1.verysorry.io:9100\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "vm2 CPU load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"vm2.verysorry.io:9100\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) or (clamp_max(irate(node_cpu{instance=\"vm2.verysorry.io:9100\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "Mysql status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"db.verysorry.io:9104\"}"
    }
   ]
  },
  {
   "title": "Queries per minute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{instance=\"db.verysorry.io:9104\"}[1m])"
    }
   ]
  },
  {
   "title": "Master server ID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id{instance=\"db.verysorry.io:9104\"}"
    }
   ]
  },
  {
   "title": "Master read only status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only{instance=\"db.verysorry.io:9104\"}"
    }
   ]
  },
  {
   "title": "Nginx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=\"www.verysorry.io:9113\"}"
    }
   ]
  },
  {
   "title": "HTTP requests per minute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(\nnginx_http_requests_total{instance=\"www.verysorry.io:9113\"}[1m])"
    }
   ]
  },
  {
   "title": "vm1 memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal{instance=\"vm1.verysorry.io:9100\"} - node_memory_MemAvailable{instance=\"vm1.verysorry.io:9100\"}) / (node_memory_MemTotal{instance=\"vm1.verysorry.io:9100\"})) * 100"
    }
   ]
  },
  {
   "title": "vm2 memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal{instance=\"vm2.verysorry.io:9100\"} - node_memory_MemAvailable{instance=\"vm2.verysorry.io:9100\"}) / (node_memory_MemTotal{instance=\"vm2.verysorry.io:9100\"})) * 100"
    }
   ]
  },
  {
   "title": "Mysql  SLAVE status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"dbslave.verysorry.io:9104\"}"
    }
   ]
  },
  {
   "title": "Queries per minute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{instance=\"dbslave.verysorry.io:9104\"}[1m])"
    }
   ]
  },
  {
   "title": "Slave server ID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id{instance=\"dbslave.verysorry.io:9104\"}"
    }
   ]
  },
  {
   "title": "Slave read only status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only{instance=\"dbslave.verysorry.io:9104\"}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select * from latency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS master status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bind_up{instance=\"dns.verysorry.io:9119\"}"
    }
   ]
  },
  {
   "title": "DNS queries per minute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{instance=\"dns.verysorry.io:9119\"}[1m])"
    }
   ]
  },
  {
   "title": "DNS slave status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "bind_up{instance=\"dns1.verysorry.io:9119\"}"
    }
   ]
  },
  {
   "title": "DNS queries per minute",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{instance=\"dns1.verysorry.io:9119\"}[1m])"
    }
   ]
  },
  {
   "title": "Haproxy vm1 status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_up{instance=\"vm1.verysorry.io:9101\"}"
    }
   ]
  },
  {
   "title": "Haproxy vm2 status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_up{instance=\"vm2.verysorry.io:9101\"}"
    }
   ]
  },
  {
   "title": "haproxy_server_up vm1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"vm1.verysorry.io:9101\", backend=\"agama\"}"
    }
   ]
  },
  {
   "title": "haproxy_server_up vm2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"vm2.verysorry.io:9101\", backend=\"agama\"}"
    }
   ]
  },
  {
   "title": "keepalived_vrrp_state vm1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"vm1.verysorry.io:9165\"}"
    }
   ]
  },
  {
   "title": "keepalived_vrrp_state vm2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"vm2.verysorry.io:9165\"}"
    }
   ]
  }
 ]
}