- name: Create user agama
  user:
    name: agama

- name: Create application directory
  file:
    path: /opt/agama
    state: directory
    owner: agama
    
- name: Install app dependencies
  apt:
    name: python3-flask-sqlalchemy,python3
    
- name: Download AGAMA application
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py
    owner: agama
    mode: '755'
