- name: Create user backup
  user: 
    name: backup
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_rsa
    password: "{{ backup_user_pass }}"

- name: Add user to grafana group
  user:
    name: backup
    groups: grafana
  when: inventory_hostname == groups['grafana'][0]

- name: Add read permission for grafana/png
  file:
    path: /var/lib/grafana/png
    mode: g+r
  when: inventory_hostname == groups['grafana'][0]

- name: Set permissions for docker folder
  file:
    path: /opt/docker
    mode: '0645'
  when: inventory_hostname == groups['grafana'][0]

- name: Set permissions for grafana_docker folder
  file:
    path: /opt/docker/grafana
    recurse: yes
    mode: '0745'
  when: inventory_hostname == groups['grafana'][0]

- name: Create backup user for MySQL
  mysql_user:
    priv: "{{ mysql_database }}.*:SELECT,SHOW VIEW,TRIGGER,LOCK TABLES"
    name: "backup"
    password: "{{ backup_mysql_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: inventory_hostname == groups['db_servers'][0]

- name: Create config file for MySQL
  template:
    src: .my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    mode: '0400'
  when: inventory_hostname == groups['db_servers'][0]

- name: Create the directories
  file:
    path: /home/backup/{{ item }}
    state: directory
    mode: '0744'
    owner: backup
    group: backup
  loop:
    - backup
    - restore
    - scripts

- name: Copy backup scripts
  template:
    src: "{{ item.name }}"
    dest: "/home/backup/scripts/{{ item.name }}"
    mode: '0700'
    owner: backup
    group: backup
  when: inventory_hostname == item.host
  loop: "{{ backup_scripts }}"

- name: Install duplicity
  apt:
    name: duplicity

- name: Schedule cron jobs
  template:
    src: cron_schedule.j2
    dest: /etc/cron.d/backup