- name: Download MySql exporter
  apt:
    name: prometheus-mysqld-exporter

- name: Ensure that user prometheus exists
  user:
    name: prometheus
    home: /var/lib/prometheus
    
- name: Copy the my.cnf file
  template:
    src: .my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    group: prometheus
    mode: '0400'
  notify: Restart mysql_exporter

- name: Create MySQL user
  mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    state: present

- name: Enable exporter
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes

