- name: Install MySQL server
  apt:
    name: mysql-server
    
- name: Copy the configuration file
  copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart MySQL

- name: Start MySQL server on boot
  service:
    name: mysql
    state: started
    enabled: yes
  
- name: Install pymysql
  apt:
    name: python3-pymysql
  
- name: MySQL database
  mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    
- name: Create MySQL user
  mysql_user:
    priv: "{{ mysql_database }}.*:ALL"
    host: "%"
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create backup user for MySQL
  mysql_user:
    priv: "{{ mysql_database }}.*:SELECT,SHOW VIEW,TRIGGER,LOCK TABLES"
    name: "backup"
    password: "{{ backup_mysql_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  #when: inventory_hostname == groups['db_servers'][0]

- name: Create config file for MySQL
  template:
    src: .my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    mode: '0400'
  #when: inventory_hostname == groups['db_servers'][0]
