- name: Install MySQL server
  apt:
    name: mysql-server
    
- name: Copy the configuration file
  template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart MySQL

- name: Start MySQL server on boot
  service:
    name: mysql
    state: started
    enabled: yes
  
- name: Install pymysql
  apt:
    name: python3-pymysql
  
- name: MySQL database
  mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: Create MySQL user
  mysql_user:
    priv: "{{ mysql_database }}.*:ALL"
    host: "%"
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MySQL replication user
  mysql_user:
    priv: "*.*:REPLICATION SLAVE"
    host: "%"
    name: "replication"
    password: "{{ mysql_replication_pass }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: inventory_hostname == groups['db_master'][0]