- name: Install node exporter and nginx
  apt:
    update_cache: yes
    name:
      - prometheus-node-exporter
      - nginx

- name: Enable node exporter
  service:
    name: prometheus-node-exporter
    enabled: yes

- name: Copy the configuration for nginx
  template:
    src: node_exporter.j2
    dest: /etc/nginx/sites-available/node_exporter.cfg
  notify: Restart nginx

- name: Create symlink to config
  file:
    src: /etc/nginx/sites-available/node_exporter.cfg
    dest: /etc/nginx/sites-enabled/default
    state: link