- name: Install node exporter and nginx
  apt:
    update_cache: yes
    name:
      - prometheus-node-exporter
      - nginx

- name: Enable node exporter
  service:
    name: prometheus-node-exporter
    enabled: yes