- name: Install bind9 exporter
  apt:
    name: prometheus-bind-exporter

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Enable the exporter
  service:
    name: prometheus-bind-exporter
    state: started
    enabled: yes
