- name: HAProxy exporter container
  docker_container:
    container_default_behavior: "compatibility"
    #privileged: yes
    name: haproxy-exporter
    image: quay.io/prometheus/haproxy-exporter:v0.9.0
    published_ports:
      - "9101:9101"
    command: '--haproxy.scrape-uri="http://{{ inventory_hostname }}.{{ zone }}:88/haproxy?stats;csv"'