- name: Install prometheus
  apt:
    name: prometheus

- name: Enable the service
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Copy the file with default argument
  template:
    src: default.j2
    dest: /etc/default/prometheus
  notify: Restart prometheus

- name: Copy the configuration file for prometheus
  template:
    src: prometheus.j2
    dest: /etc/prometheus/prometheus.yml 
  notify: Restart prometheus