- name: Enable nginx
  service:
    name: nginx
    enabled: yes

- name: Copy the nginx config
  template:
    src: nginx_config.j2
    dest: /etc/nginx/conf.d/reverse_proxies
  notify: Restart nginx