- name: Install pip
  apt:
    name: python3-pip

- name: Install dnspython
  pip:
    name: dnspython

- name: Update DNS cnames
  nsupdate:
    key_algorithm: hmac-sha256
    key_name: "{{ dns_update }}"
    key_secret: "{{ dns_update_secret }}"
    server: "{{ hostvars[groups['dns_masters'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ zone }}"
    type: "CNAME"
    record: "{{ item.cname }}"
    value: "{{ item.real }}"
  loop: "{{ dns_cnames }}"