- name: Stop service
  service:
    name: systemd-resolved
    state: stopped

- name: Copy resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    
- name: Start service
  service:
    name: systemd-resolved
    state: started