- name: Install DNS server
  apt:
    name: bind9

- name: Enable DNS server
  service:
    name: bind9
    state: started
    enabled: yes
    
- name: Configure master zone
  template:
    src: db.j2
    dest: /var/lib/bind/db.{{ startup }}
    force: no
  when: inventory_hostname in groups['dns_masters']
  notify: Reload master zone
  
- name: Configure DNS
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart DNS server
    