- name: Create needed directories
  file:
    path: /opt/agama
    state: directory

- name: Transfer docker file for agama
  template:
    src: agama_docker.j2
    dest: /opt/agama/Dockerfile
  register: dockerfile

- name: Remove agama container
  docker_container:
    container_default_behavior: "compatibility"
    name: agama
    state: absent
  when: dockerfile is changed

- name: Remove image
  docker_image:
    state: absent
    name: agama
  when: dockerfile is changed

- name: Build docker image
  docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama
      pull: yes

- name: Deploy agama container
  docker_container:
    container_default_behavior: "compatibility"
    name: agama
    image: agama
    published_ports:
      - "{{ agama_port }}:8000"
    env:
      AGAMA_DATABASE_URI: "mysql://{{ mysql_user }}:{{ mysql_password }}@db.verysorry.io:3306/{{ mysql_database }}"
